methods:
     1:
       algorithm: "rb_ipop_cma_esr_csa"
       params: 
        - "last_its_type"
       values:
        - "ave"
ids:
  - "rb-ipop-cma-es-csa-ave"
probnum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
dims:
  - 10
cec: 21
repnum: 30
suite: "basic"
cpupc: 0.75
source: "~/cec2020/R"
dest: "~/cec2020/data"
